#include <Common/CharInfo.h>

using namespace vc::charinfo;

/// ISO-8859-1 Char Information Table based on LRM 15.2
const uint16_t vc::charinfo::CharInfo[256] {
    0, 0, 0, 0, 0, 0, 0, 0,
    0, CHAR_HWSPACE, CHAR_VWSPACE, CHAR_VWSPACE, CHAR_VWSPACE, CHAR_VWSPACE, 0, 0,
    //0x10
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    //0x20
    CHAR_SPACE, CHAR_OTHSPEC, CHAR_DELIM, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_DELIM, CHAR_DELIM,
    CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM,
    //0x30
    CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT,
    CHAR_DIGIT, CHAR_DIGIT, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM,
    //0x40
    CHAR_DELIM, CHAR_XUPPER, CHAR_XBUPPER, CHAR_XUPPER, CHAR_XBUPPER, CHAR_XUPPER, CHAR_XUPPER, CHAR_UPPER,
    CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_BUPPER,
    // 0x50
    CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_QUPPER, CHAR_UPPER, CHAR_QUPPER, CHAR_UPPER, CHAR_UPPER,
    CHAR_BUPPER, CHAR_UPPER, CHAR_UPPER, CHAR_DELIM, CHAR_DELIM, CHAR_DELIM, CHAR_OTHSPEC, CHAR_UNDERLINE,
    //0x60
    CHAR_OTHSPEC, CHAR_XLOWER, CHAR_XBLOWER, CHAR_XLOWER, CHAR_XBLOWER, CHAR_XLOWER, CHAR_XLOWER, CHAR_LOWER,
    CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_BLOWER,
    //0x70
    CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_QLOWER, CHAR_LOWER, CHAR_QLOWER, CHAR_LOWER, CHAR_LOWER,
    CHAR_BLOWER, CHAR_LOWER, CHAR_LOWER, CHAR_OTHSPEC, CHAR_DELIM, CHAR_OTHSPEC, CHAR_OTHSPEC, 0,
    //0x80
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    //0x90
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    //0xA0
    CHAR_SPACE, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC,
    CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC,
    //0xB0
    CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC,
    CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC, CHAR_OTHSPEC,
    //0xC0
    CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER,
    CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER,
    //0xD0
    CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_OTHSPEC,
    CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_UPPER, CHAR_LOWER,
    //0x
    CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER,
    CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER,
    //0xF
    CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_OTHSPEC,
    CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER, CHAR_LOWER
};
